

- name: Installed Redis Repos
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true

- name: Enable Redis 6.2 version
  ansible.builtin.shell: yum module enable redis:remi-6.2 -y

- name: Update Redis Listen Address - /etc/redis.conf
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'


- name: Update Redis Listen Address - /etc/redis/redis.conf
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0

- name: Start & Enable Redis Service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes

